version: "3.8"

services:
  airflow:
    image: lucastercas/airflow:dev
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_USER: test_user
      POSTGRES_DB: airflow
