---
name: Moodle Docker Image Upload
on:
  push:
    paths:
      - 'moodle/**'
jobs:
  push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        working-directory: ./jenkins
        run: DOCKER_BUILDKIT=1 make build
      - name: Push
        working-directory: ./jenkins
        run: make push
